const faker = require('faker');
const fs = require('fs');

const data_json = {
   zipCode: [],
   city: [],
   cityPrefix: [],
   citySuffix: [],
   streetName: [],
   streetAddress: [],
   streetSuffix: [],
   streetPrefix: [],
   secondaryAddress: [],
   county: [],
   country: [],
   countryCode: [],
   state: [],
   stateAbbr: [],
   latitude: [],
   longitude: [],
   color: [],
   department: [],
   productName: [],
   price: [],
   productAdjective: [],
   productMaterial: [],
   product: [],
   suffixes: [],
   companyName: [],
   companySuffix: [],
   catchPhrase: [],
   bs: [],
   catchPhraseAdjective: [],
   catchPhraseDescriptor: [],
   catchPhraseNoun: [],
   bsAdjective: [],
   bsBuzz: [],
   bsNoun: [],
   column: [],
   type: [],
   collation: [],
   engine: [],
   past: [],
   future: [],
   between: [],
   recent: [],
   month: [],
   weekday: [],
   account: [],
   accountName: [],
   mask: [],
   amount: [],
   transactionType: [],
   currencyCode: [],
   currencyName: [],
   currencySymbol: [],
   bitcoinAddress: [],
   iban: [],
   bic: [],
   abbreviation: [],
   adjective: [],
   noun: [],
   verb: [],
   ingverb: [],
   phrase: [],
   randomize: [],
   slugify: [],
   replaceSymbolWithNumber: [],
   replaceSymbols: [],
   shuffle: [],
   mustache: [],
   createCard: [],
   contextualCard: [],
   userCard: [],
   createTransaction: [],
   image: [],
   avatar: [],
   imageUrl: [],
   abstract: [],
   animals: [],
   business: [],
   cats: [],
   city: [],
   food: [],
   nightlife: [],
   fashion: [],
   people: [],
   nature: [],
   sports: [],
   technics: [],
   transport: [],
   dataUri: [],
   avatar: [],
   email: [],
   exampleEmail: [],
   userName: [],
   protocol: [],
   url: [],
   domainName: [],
   domainSuffix: [],
   domainWord: [],
   ip: [],
   ipv6: [],
   userAgent: [],
   color: [],
   mac: [],
   password: [],
   word: [],
   words: [],
   sentence: [],
   slug: [],
   sentences: [],
   paragraph: [],
   paragraphs: [],
   text: [],
   lines: [],
   firstName: [],
   lastName: [],
   findName: [],
   jobTitle: [],
   prefix: [],
   suffix: [],
   title: [],
   jobDescriptor: [],
   jobArea: [],
   jobType: [],
   phoneNumber: [],
   phoneNumberFormat: [],
   phoneFormats: [],
   number: [],
   arrayElement: [],
   objectElement: [],
   uuid: [],
   boolean: [],
   word: [],
   words: [],
   image: [],
   locale: [],
   alphaNumeric: [],
   fileName: [],
   commonFileName: [],
   mimeType: [],
   commonFileType: [],
   commonFileExt: [],
   fileType: [],
   fileExt: [],
   semver: [],
};

for (const nameOfFaker in faker) {
   for (const key in faker[nameOfFaker]) {
      if (faker[nameOfFaker].hasOwnProperty(key)) {
         if (typeof faker[nameOfFaker][key] == 'function' && data_json[key] !== undefined) {
            for (let index = 0; index < 3; index++) {
               for (let j = 0; j < 10000; j++) {
                  data_json[key].push(faker[nameOfFaker][key]());
               }

               data_json[key] = [...new Set(data_json[key])];
            }
         }
      }
   }
}

let data_write = JSON.stringify(data_json);
fs.writeFileSync('faker.json', data_write);
